INSERT INTO users (name, age) VALUES ("Bobbi", 56);
INSERT INTO users (name, age) VALUES ("Rodney", 56);
INSERT INTO users (name, age) VALUES ("Patti", 54);
INSERT INTO users (name, age) VALUES ("Wade", 29);
INSERT INTO users (name, age) VALUES ("Jennifer", 27);
INSERT INTO users (name, age) VALUES ("Alyson", 28);
INSERT INTO users (name, age) VALUES ("Emma", 6);
INSERT INTO users (name, age) VALUES ("Harper", 1);
INSERT INTO users (name, age) VALUES ("Addi", 7);
INSERT INTO users (name, age) VALUES ("Bill", 40);
INSERT INTO users (name, age) VALUES ("Anna", 34);
INSERT INTO users (name, age) VALUES ("Cale", 12);
INSERT INTO users (name, age) VALUES ("Ayson", 10);
INSERT INTO users (name, age) VALUES ("Finn", 4);
INSERT INTO users (name, age) VALUES ("Maddi", 18);
INSERT INTO users (name, age) VALUES ("Charlie", 75);
INSERT INTO users (name, age) VALUES ("Mary Beth", 75);
INSERT INTO users (name, age) VALUES ("Mike", 56);
INSERT INTO users (name, age) VALUES ("Brie", 23);
INSERT INTO users (name, age) VALUES ("Lauren", 21);

INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Slapchop", "Household", 10000, 03/17);